all:: MAPIStorePropertySelectors.m MAPIStorePropertySelectors.h

MAPIStorePropertySelectors.m MAPIStorePropertySelectors.h: gen-property-selectors.py code-MAPIStorePropertySelectors.m code-MAPIStorePropertySelectors.h
	@echo " Auto-generating MAPIStorePropertySelectors.[hm]..."
	@$(PYTHON) ./gen-property-selectors.py -o MAPIStorePropertySelectors $(LIBMAPISTORE_CFLAGS)
