INSERT INTO SOGo_folder_info  
  ( c_path, c_path1, c_path2, c_path3, c_path4, c_foldername,  
    c_location, c_quick_location, c_folder_type )  
VALUES  
  ( '/Users/test.et.di.cete-lyon/Contacts',  
    'Users', 
    'test.et.di.cete-lyon', 
    'Contacts', 
     NULL, 
    'Contacts',  
    'http://postgres:@agenor-db:5432/test/SOGo_test_contacts_blob',  
    'http://postgres:@agenor-db:5432/test/SOGo_test_contacts_quick',  
    'Contact' ); 
