--
-- (C) 2004 SKYRIX Software AG
--

DELETE FROM SOGo_test_contacts_blob
  WHERE c_name = 'contact_donald';
DELETE FROM SOGo_test_contacts_quick
  WHERE c_name = 'contact_donald';

INSERT INTO SOGo_test_contacts_blob
  ( c_name, c_creationdate, c_lastmodified, c_version, c_content )
VALUES (
  'contact_donald',
  928383,
  928383,
  1,
  '{ 
     givenName="Donald"; cn="Donald Duck"; sn="Duck"; 
     l="Entenhausen";
     mail="dd@entenhausen.com";
     o="Geldspeicher AG";
     ou="Support";
     telephoneNumber="0190-1234567";
   }'
);

INSERT INTO SOGo_test_contacts_quick
  ( c_name, givenname, cn, sn, l, mail, o, ou, telephoneNumber )
VALUES (
  'contact_donald', 'Donald', 'Donald Duck', 'Duck', 'Entenhausen',
  'dd@entenhausen.com', 'Geldspeicher AG', 'Support',
  '0190-1234567'
);
