# postprocessing

$(TYPEMODELS_DIR) :
	$(MKDIRS) $(TYPEMODELS_DIR)

ocs-typemodels : $(TYPEMODELS_DIR) $(libGDLContentStore_TYPEMODELS)
	@(if [ "$(libGDLContentStore_TYPEMODELS)" != "" ]; then \
	  echo "Copying type models into install path ..."; \
          for ff in $(libGDLContentStore_TYPEMODELS); do \
	    cp $$ff $(TYPEMODELS_DIR)/$$ff; \
          done; \
	fi)

after-install :: ocs-typemodels

