# $Id$

include $(GNUSTEP_MAKEFILES)/common.make


SUBPROJECT_NAME = NGExtensions


ADDITIONAL_INCLUDE_DIRS += -I..


NGExtensions_SUBPROJECTS = \
	NGLogging


-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/subproject.make
-include GNUmakefile.postamble
