# GNUstep makefile

-include ../config.make
include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = \
	SOGo		\
	Appointments	\
	Contacts	\
	Mailer		\
	Sieve		\

include $(GNUSTEP_MAKEFILES)/aggregate.make
