include ../../config.make
include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = teststrings 
teststrings_OBJC_FILES += \
	teststrings.m

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/tool.make
