# compile settings

ADDITIONAL_CPPFLAGS += \
        -DSOGO_MAJOR_VERSION=$(MAJOR_VERSION) \
        -DSOGO_MINOR_VERSION=$(MINOR_VERSION) \
        -DSOGO_SUBMINOR_VERSION=$(SUBMINOR_VERSION) \
	-DSOGO_LIBDIR="@\"$(SOGO_LIBDIR)\""

ADDITIONAL_INCLUDE_DIRS += \
	-D_GNU_SOURCE -I../../SOPE/ -I../../SoObjects/

ADDITIONAL_LIB_DIRS += \
	-L../../SoObjects/SOGo/SOGo.framework -lSOGo \
	-L../../OGoContentStore/$(GNUSTEP_OBJ_DIR)/ -lOGoContentStore \
	-L../../SOPE/GDLContentStore/$(GNUSTEP_OBJ_DIR)/ -lGDLContentStore \
	-L../../SOPE/NGCards/$(GNUSTEP_OBJ_DIR)/ -lNGCards \
        -L/usr/local/lib -L/usr/lib -lEOControl -lNGStreams -lNGMime -lNGExtensions

ADDITIONAL_LDFLAGS += -Wl,--no-as-needed
