# compilation settings

MAPDIR="$(SOPE_SAXMAPPINGS)"

mappings-dir ::
	$(MKDIRS) $(MAPDIR)

after-install :: mappings-dir
	cp NGCards.xmap $(MAPDIR)
	-mkdir -p $(GNUSTEP_LIBRARY)/Libraries/Resources/NGCards
	cp -dpR TimeZones $(GNUSTEP_LIBRARY)/Libraries/Resources/NGCards
