# compilation settings

MAPDIR="$(SOPE_SAXMAPPINGS)"

mappings-dir ::
	$(MKDIRS) $(MAPDIR)

after-install :: mappings-dir
	${INSTALL_DATA} NGCards.xmap $(MAPDIR)
	$(MKDIRS) $(GNUSTEP_LIBRARY)/Libraries/Resources/NGCards
	cp -R TimeZones $(GNUSTEP_LIBRARY)/Libraries/Resources/NGCards
