#!/bin/bash

for file in `git status --porcelain | awk '/^[A ][ M].*Localizable.strings/ { printf $2 " " }'`; do
  file $file | fgrep UTF-8 1>/dev/null
  if [ 1 -eq $? ]; then
    echo $file
    iconv -f utf16 -t utf8 $file > ${file}.utf8
    mv -f ${file}.utf8 $file
  fi
done
