#!/bin/sh

# SOGOSPOOL must match the value of the configuration parameter SOGoMailSpoolPath
SOGOSPOOL=/var/spool/sogo

/usr/sbin/tmpwatch 24 "$SOGOSPOOL"
find "$SOGOSPOOL" -mindepth 1 -type d -user sogo -empty -delete > /dev/null
