# GNUstep makefile

-include ../config.make
include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS += \
	SOGoUI			\
	SOGoElements		\
	Common			\
	Contacts		\
	MailPartViewers         \
	MailerUI		\
	MainUI			\
	PreferencesUI		\
	Scheduler		\
	AdministrationUI	\
	Templates		\
	WebServerResources

include $(GNUSTEP_MAKEFILES)/aggregate.make
