# GNUstep makefile

-include ../config.make
include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS += \
	Common		\
	Contacts	\
	MailerUI	\
	MailPartViewers	\
	MainUI		\
	PreferencesUI	\
	Scheduler	\
	SOGoUI		\
	Templates

include $(GNUSTEP_MAKEFILES)/aggregate.make
